### ISSUE TITLE
Should things like just be uploaded to Bintray/JCenter instead of putting binaries into source control?

### ISSUE THREAD

**Issue by cdancy** [pegasystems/pega-alertanalyzer#1]

**Comment by dcasavant** [comment]
Yes. However in this case we do have the source too. Check out my project fork. I’ll clean it up a bit and then pull it in here. 

Still will need the standard CI suite applied, but I’m not very familiar with how the project should be built...

**Comment by cdancy** [comment]
@dcasavant let me know when you have things ready to go and I can look to wire up the gradle/publishing parts to Bintray.

**Comment by dcasavant** [comment]
Adding source in a PR
