### ISSUE TITLE
Is this supposed to output a war file?

### ISSUE THREAD

**Issue by cdancy** [pegasystems/pega-alertanalyzer#4]
Project has been converted to gradle with the stub provided by [gradle-multi-project-example](https://github.com/project-aries/gradle-multi-project-example). I noticed a `WebContent` directory containing various web related files and was wondering what was up and/or what this is?

Also ... take a look at the new structure and let me know what you think.

EDIT: it should be noted that VERY aggressive checking is enabled for the attached static analysis tools and as such this code, as it is now, is in pretty rough shape.

**Comment by dcasavant** [comment]
The CI pipeline is currently failing as well.

@cdancy Why is it that we are getting an error tag from Travis-CI on failure? Is that a misconfig on my end? Shouldn't it be a failure tag?

**Comment by cdancy** [comment]
@dcasavant this is a "feature" of travis for better or worse :) Just added a change to the travis file to side-step this feature and get an actual fail.

**Comment by feenr** [comment]
@cdancy saw that you enabled a few static analysis tools, but they are all failing miserably. I started working through the checkstyle warnings.
https://github.com/feenr/pega-alertanalyzer

Were you able to generate the war file, even if it's not part of the build script yet?

Would you be willing to remove those static analysis tasks from the Travis scripts and track them individually as issues, just so it has a passing build?

**Comment by cdancy** [comment]
Yeah I left these in place so that folks working on this project, whenever they eventually got around to it, would be forced to clean up the code base so that individuals stumbling upon this project on the internets would not think we are churning out un-production level code.

As for removing these checks you can simply comment out the relevant lines in the `gradle/projects.gradle` file that you don't want it to check for.

```
    apply from: "$rootDir/gradle/jacoco.gradle"
    // apply from: "$rootDir/gradle/pmd.gradle"
    apply from: "$rootDir/gradle/checkstyle.gradle"
    //apply from: "$rootDir/gradle/findbugs.gradle"
```
