### ISSUE TITLE
Add a readme which explains how to use this project

### ISSUE THREAD

**Issue by feenr** [pegasystems/pega-alertanalyzer#9]
This project requires a readme that explains how to deploy this project. It's not at all obvious since it needs to be deployed as a war on an app server.

**Comment by rootExplorr** [comment]
Can you describe the process of deployment ?

**Comment by feenr** [comment]
The war can be generated by executing the ```./gradlew build``` command. It will be placed in the ```/build/libs``` folder. The war can then be deployed on a running tomcat server by dropping it into the webapps folder, or by using the web interface. I'll also update the Readme shortly with instructions for running in docker.

**Comment by feenr** [comment]
@ramasCoder I didn't see your PR for adding a dockerfile until I had worked on it myself. Please see:
https://github.com/pegasystems/pega-alertanalyzer/pull/12

**Comment by rootExplorr** [comment]
Not an issue , would be happy to contribute next time 💯

**Comment by feenr** [comment]
@ramasCoder If you're still interested to contribute, you can try to use the docker plugin as suggested by @cdancy here:
https://github.com/pegasystems/pega-alertanalyzer/pull/12#issuecomment-435943666
